openapi: 3.1.0
info:
  title: Mon API Serverless
  description: API pour le TP-2 hébergée sur Azure.
  version: 1.0.0

# C'est ici qu'on dit à la passerelle où se trouve 
# notre backend (votre Container App)
servers:
  - url: https://mon-api-flask-app.bravesmoke-b5c90913.westeurope.azurecontainerapps.io

# Description de tous les points de terminaison (routes)
paths:
  # Notre unique route : /hello
  /hello:
    get:
      summary: Renvoie un message de bienvenue
      responses:
        # Code de succès
        '200':
          description: Une réponse JSON simple.
          content:
            application/json:
              schema:
                # Décrit le JSON que nous renvoyons
                type: object
                properties:
                  message:
                    type: string
                    example: "Bonjour, monde du serverless!"